### ISSUE TITLE
fattoriale

### ISSUE THREAD

**Issue by FabioZTessitore** [christian99salerno/exp#1]
in attesa

**Comment by christian99salerno** [comment]
si prof non mi ricordo cos'è perciò mi sono scoraggiato

**Comment by FabioZTessitore** [comment]
E fare una ricerca?

Il gio 30 mag 2019, 09:26 christian99salerno <notifications@github.com> ha
scritto:

**Comment by christian99salerno** [comment]
adesso vedo

**Comment by FabioZTessitore** [comment]
Tra l'altro è un richiamo ad un esercizio già fatto, ci servirà per fare
altre cose

Il gio 30 mag 2019, 09:30 christian99salerno <notifications@github.com> ha
scritto:

**Comment by christian99salerno** [comment]
capito

**Comment by christian99salerno** [comment]
e l'ho copiato quello vecchio, adesso credo che dovrò modificarlo

**Comment by christian99salerno** [comment]
ah il fattoriale: è il prodotto di un numero per tutti i suoi antecedenti; sembra facile

**Comment by FabioZTessitore** [comment]
Si

Il gio 30 mag 2019, 09:34 christian99salerno <notifications@github.com> ha
scritto:

**Comment by christian99salerno** [comment]
ma sempre intero il numero che viene letto giusto?

**Comment by christian99salerno** [comment]
adesso lo carico

**Comment by FabioZTessitore** [comment]
il programma funziona, ma per evitare di dover ripensare la logica negli esercizi successivi, fai partire il fattoriale da 1 e fai arrivare il ciclo a n

**Comment by christian99salerno** [comment]
ok
